if [[ -f $HOME/.antigen/antigen.zsh ]]; then
  source $HOME/.antigen/antigen.zsh

  ## Load the oh-my-zsh's library.
  antigen use oh-my-zsh

  antigen bundle git
  antigen bundle command-not-found
  antigen bundle ssh-agent

  ## Syntax highlighting bundle.
  antigen bundle zsh-users/zsh-syntax-highlighting

  antigen theme agnoster/agnoster-zsh-theme agnoster

  ## Tell Antigen that you're done.
  antigen apply
fi

bindkey -v

# Preserve environment when sudoing
alias sudo=sudo -E

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
