if [[ -f $HOME/.antigen/antigen.zsh ]]; then
  source $HOME/.antigen/antigen.zsh

  ## Load the oh-my-zsh's library.
  antigen use oh-my-zsh

  antigen bundle git
  antigen bundle ssh-agent

  FZF_BASE=/usr/bin
  antigen bundle fzf

  ## Syntax highlighting bundle.
  antigen bundle zsh-users/zsh-syntax-highlighting

  antigen theme agnoster/agnoster-zsh-theme agnoster

  ## Tell Antigen that you're done.
  antigen apply
fi

bindkey -v

# Preserve environment when sudoing
alias sudo=sudo -E

# FZF Integration
if [[ "$(uname)" = "Darwin" ]; then
  [ -f /usr/local/opt/fzf/shell/completion.zsh ] && source /usr/local/opt/fzf/shell/completion.zsh
  [ -f /usr/local/opt/fzf/shell/key-bindings.zsh ] && source /usr/local/opt/fzf/shell/key-bindings.zsh
elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
  [ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh
  [ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh
fi

## Lazy Load NVM
if [ -d "~/.nvm" ]; then
  declare -a NODE_GLOBALS=(`find ~/.nvm/versions/node -maxdepth 3 -type l -wholename '*/bin/*' | xargs -n1 basename | sort | uniq`)

  NODE_GLOBALS+=("node")
  NODE_GLOBALS+=("nvm")

  load_nvm () {
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  }

  for cmd in "${NODE_GLOBALS[@]}"; do
      eval "${cmd}(){ unset -f ${NODE_GLOBALS}; load_nvm; ${cmd} \$@ }"
  done
fi

eval "$(rbenv init -)"
